SELECT 
  ID, 
  AGE, 
  M.COINS_NEEDED, 
  M.POWER 
FROM 
  (
    SELECT 
      CODE, 
      POWER, 
      MIN(COINS_NEEDED) AS COINS_NEEDED 
    FROM 
      WANDS 
    GROUP BY 
      CODE, 
      POWER
  ) AS M 
  JOIN WANDS AS W ON M.CODE = W.CODE 
  AND M.POWER = W.POWER 
  AND M.COINS_NEEDED = W.COINS_NEEDED 
  JOIN WANDS_PROPERTY AS P ON M.CODE = P.CODE 
WHERE 
  P.IS_EVIL = 0 
ORDER BY 
  M.POWER DESC, 
  AGE DESC;
