SELECT CON.CONTEST_ID, CON.HACKER_ID, CON.NAME, 
SUM(SG.TOTAL_SUBMISSIONS), SUM(SG.TOTAL_ACCEPTED_SUBMISSIONS), 
SUM(VG.TOTAL_VIEWS), SUM(VG.TOTAL_UNIQUE_VIEWS)
FROM CONTESTS AS CON
JOIN COLLEGES AS COL ON CON.CONTEST_ID = COL.CONTEST_ID
JOIN CHALLENGES AS CHA ON CHA.COLLEGE_ID = COL.COLLEGE_ID
LEFT JOIN
(SELECT SS.CHALLENGE_ID, SUM(SS.TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS, SUM(SS.TOTAL_ACCEPTED_SUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS FROM SUBMISSION_STATS AS SS GROUP BY SS.CHALLENGE_ID) AS SG
ON CHA.CHALLENGE_ID = SG.CHALLENGE_ID
LEFT JOIN
(SELECT VS.CHALLENGE_ID, SUM(VS.TOTAL_VIEWS) AS TOTAL_VIEWS, SUM(VS.TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS
FROM VIEW_STATS AS VS GROUP BY VS.CHALLENGE_ID) AS VG
ON CHA.CHALLENGE_ID = VG.CHALLENGE_ID
GROUP BY CON.CONTEST_ID, CON.HACKER_ID, CON.NAME
HAVING SUM(SG.TOTAL_SUBMISSIONS) +
       SUM(SG.TOTAL_ACCEPTED_SUBMISSIONS) +
       SUM(VG.TOTAL_VIEWS) +
       SUM(VG.TOTAL_UNIQUE_VIEWS) > 0
ORDER BY CON.CONTEST_ID;
