SELECT 
  C.COMPANY_CODE, 
  C.FOUNDER, 
  COUNT(DISTINCT L.LEAD_MANAGER_CODE), 
  COUNT(DISTINCT S.SENIOR_MANAGER_CODE), 
  COUNT(DISTINCT M.MANAGER_CODE), 
  COUNT(DISTINCT E.EMPLOYEE_CODE) 
FROM 
  COMPANY C 
  JOIN LEAD_MANAGER L ON C.COMPANY_CODE = L.COMPANY_CODE 
  JOIN SENIOR_MANAGER S ON L.LEAD_MANAGER_CODE = S.LEAD_MANAGER_CODE 
  JOIN MANAGER M ON S.SENIOR_MANAGER_CODE = M.SENIOR_MANAGER_CODE 
  JOIN EMPLOYEE E ON M.MANAGER_CODE = E.MANAGER_CODE 
GROUP BY 
  C.COMPANY_CODE, 
  C.FOUNDER 
ORDER BY 
  C.COMPANY_CODE;
