SET 
  @R1 = 0, 
  @R2 = 0, 
  @R3 = 0, 
  @R4 = 0;
SELECT 
  MIN(DOCTOR), 
  MIN(PROFESSOR), 
  MIN(SINGER), 
  MIN(ACTOR) 
FROM 
  (
    SELECT 
      CASE OCCUPATION WHEN 'DOCTOR' THEN @R1 := @R1 + 1 WHEN 'PROFESSOR' THEN @R2 := @R2 + 1 WHEN 'SINGER' THEN @R3 := @R3 + 1 WHEN 'ACTOR' THEN @R4 := @R4 + 1 END AS ROWLINE, 
      CASE WHEN OCCUPATION = 'DOCTOR' THEN NAME END AS DOCTOR, 
      CASE WHEN OCCUPATION = 'PROFESSOR' THEN NAME END AS PROFESSOR, 
      CASE WHEN OCCUPATION = 'SINGER' THEN NAME END AS SINGER, 
      CASE WHEN OCCUPATION = 'ACTOR' THEN NAME END AS ACTOR 
    FROM 
      OCCUPATIONS 
    ORDER BY 
      NAME
  ) AS T 
GROUP BY 
  ROWLINE;

